name: Deno test

on:
  schedule:
    - cron: "0 9 * * 6"
  push:
    branches:
      - master
    paths:
      - "**/*.ts"
      - ".github/workflows/deno-test.yml"
  workflow_dispatch:

defaults:
  run:
    shell: bash --noprofile --norc -eo pipefail {0}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global core.autocrlf false
        if: runner.os == 'Windows'
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Type check
        run: deno task check
